// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnPDO-Dv818bJUMVzd7uRvx4IawgVSJo8',
    appId: '1:830315028496:web:0218f37f97656820206a95',
    messagingSenderId: '830315028496',
    projectId: 'finder-9959b',
    authDomain: 'finder-9959b.firebaseapp.com',
    storageBucket: 'finder-9959b.firebasestorage.app',
    measurementId: 'G-7FL2GS38V8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-p5v49bwIKaKHigaYy6_Pj-VvDvG6L1Y',
    appId: '1:830315028496:android:e6bb8782cdfc1615206a95',
    messagingSenderId: '830315028496',
    projectId: 'finder-9959b',
    storageBucket: 'finder-9959b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfXuQUuruW42xYh0o4DLBd0dEqgMsArD4',
    appId: '1:830315028496:ios:33d4aa83efabfad8206a95',
    messagingSenderId: '830315028496',
    projectId: 'finder-9959b',
    storageBucket: 'finder-9959b.firebasestorage.app',
    iosClientId: '830315028496-n80fdj42gdhaq9ngdv9bko9405mntms4.apps.googleusercontent.com',
    iosBundleId: 'com.example.finder',
  );
}
